import type { Metadata } from "next";
import "./globals.css";
import { CounterContextProvider } from "@/context/CounterContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CounterContextProvider>
        <body>{children}</body>
      </CounterContextProvider>
    </html>
  );
}
